

export const rows = [
  {
    id: 1,
    Name: "Mohamad",
    Email: "mohamadAljaber@gmail.com",
    Age: 18,
    Phone: 94762168,
    access: "Admin",
  },
  {
    id: 2,
    Name: "Ali",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "Admin",
  },
  {
    id: 3,
    Name: "Reem ",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "User",
  },
  {
    id: 4,
    Name: "Salem",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "User",
  },
  {
    id: 5,
    Name: "Housam ",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "Manager",
  },
  {
    id: 6,
    Name: "Omar",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "User",
  },
  {
    id: 7,
    Name: "Tasmin",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "Manager",
  },
  {
    id: 8,
    Name: "Yousef",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "User",
  },
  {
    id: 9,
    Name: "Ahmad",
    Email: "mohamadAljaber@gmail.com",
    Age: 28,
    Phone: 94762168,
    access: "Manager",
  },
];
